/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import java.util.Scanner;

public class App {


  // 애플리케이션 클래스 App을 실행할 때 다음 변수를 미리 준비해 둔다 = class field = static field
  // JVM 종료될 때 함께 사라짐..
  static final String ANSI_CLEAR = "\033[0m";
  static final String ANSI_BOLD_RED = "\033[1;31m";
  static final String ANSI_RED = "\033[0;31m";
  static final String APP_TITLE = ANSI_BOLD_RED + "[과제관리 시스템]" + ANSI_CLEAR;
  static final String[] MENUS = new String[]{
      "1. 과제",
      "2. 게시글",
      "3. 도움말",
      ANSI_RED + "4. 종료" + ANSI_CLEAR
  };

  public static void main(String[] args) {
    printMenu();
    java.util.Scanner keyIn = new java.util.Scanner(System.in);

    loop:
    while (true) {
      String input = prompt(keyIn);

      switch (input) {
        case "1":
          System.out.println("과제입니다.");
          break;
        case "2":
          System.out.println("게시글입니다.");
          break;
        case "3":
          System.out.println("도움말입니다.");
          break;
        case "4":
          System.out.println("종료합니다.");
          break loop;
        case "menu":
          printMenu();
          break;
        default:
          System.out.println("메뉴 번호가 옳지 않습니다.");
      }
    }

    keyIn.close();
  }

  // 로컬 변수
  static void printMenu() {
    // ANSI 코드와 App 제목, 메뉴를 저장한 변수를 메서드 안에 두는 대신
    // 클래스 블록 안에 두면
    // printMenu()를 호출할 때마다 변수를 만들지 않기 때문에
    // 실행속도나 메모리 부분에서 훨씬 효율적
    //보통 메서드 호출될때마다 값이 바뀌는 변수가 아니라 고정 값을 받는 변수인 경우
    //메서드 밖에 두는 것이 좋다.
    System.out.println(APP_TITLE);
    System.out.println();
    for (String menu : MENUS) {
      System.out.println(menu);
    }
  }

  static String prompt(Scanner keyIn) {
    System.out.print("$ ");
    return keyIn.nextLine();
  }

}





